[package]
name = "deno-bindgen2-common"
version = "0.1.0"
edition.workspace = true


[features]
default = ["macro", "cli"]
macro = []
cli = []

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
