[package]
name = "deno-bindgen2-common"
version = "0.1.0"
edition.workspace = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
prettyplease.workspace = true

[features]
cli = []
macro = []
