[package]
name = "deno-bindgen2-common"
version = "1.0.0"
edition.workspace = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
deno_ast.workspace = true
dprint-plugin-typescript.workspace = true

[dev-dependencies]
prettyplease.workspace = true

[features]
macro = []
cli = []
