[package]
name = "deno-bindgen2-macro"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
deno-bindgen2-common.workspace = true
quote.workspace = true
syn.workspace = true

# proc-macro2.workspace = true

# proc-macro-error.workspace = true
# anyhow.workspace = true