[package]
name = "deno-bindgen2-macro"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
deno-bindgen2-common = { workspace = true, features = ["macro"] }
