[package]
name = "deno-bindgen2-macro"
version = "1.0.0"
edition.workspace = true
description = "Macros for the `deno_bindgen2` crate"
repository.workspace = true
license-file.workspace = true

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
deno-bindgen2-common = { workspace = true, features = ["macro"] }
