[package]
name = "deno-bindgen2-cli"
version = "1.0.0"
edition.workspace = true

[[bin]]
name = "deno-bindgen2"
path = "src/main.rs"

[dependencies]
deno-bindgen2-common = { workspace = true, features = ["cli"]}

clap.workspace = true
inquire.workspace = true
cargo_metadata.workspace = true
